### ISSUE TITLE
missing readline in S3OpenRead

### ISSUE THREAD

**Issue by ziky90** [piskvorky/smart_open#27] opened 2015-08-07 08:50 UTC
Missing readline in S3OpenRead is related to and more in detail explained in https://github.com/piskvorky/gensim/issues/421

**Comment by piskvorky** [comment] 2015-08-07 10:36
Closing as duplicate of #13 .

**Closed by piskvorky** 2015-08-07 10:36 UTC

**Comment by piskvorky** [comment] 2015-09-08 14:34
@ziky90 can you add this?

**Comment by ziky90** [comment] 2015-09-08 14:44
@piskvorky Where should I add this?

**Comment by piskvorky** [comment] 2015-09-08 16:43
In `S3OpenRead`... or what do you mean?

**Comment by ziky90** [comment] 2015-09-09 07:20
Oh sorry I though that this is a different issue. 
I can try to look up the default behaviour of `readline()` and try to implement it during September.
